services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memaro
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: memaro
    restart: always
    depends_on:
      - postgres
      - qdrant
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      QDRANT_URL: http://qdrant:6333
    ports:
      - "2999:2999"
    volumes:
      - ./data:/app/data

configs:
  qdrant_config:
    content: |
      log_level: INFO
